### ISSUE TITLE
Fail to send an email when TLS is enabled

### ISSUE THREAD

**Issue by Stygmates** [tweedegolf/mailcrab#111]
Hi,
Thank you for the tool.
With the latest version, I can't seem to send an email when TLS is enabled, the sending loops indefinitely, this wasn't the case with previous versions.

Steps to reproduce:
- Run the docker container:
```
docker run --rm --env ENABLE_TLS_AUTH=true -p 1080:1080 -p 1025:1025 marlonb/mailcrab:latest
```
- Send the email:
```
curl smtp://127.0.0.1:1025 --mail-from myself@example.com --mail-rcpt receiver@example.com --upload-file samples/normal.email --user 'user:pass'
```

It does work when using:
```
docker run --rm --env ENABLE_TLS_AUTH=true -p 1080:1080 -p 1025:1025 marlonb/mailcrab:latest
```

**Comment by stappersg** [comment]
![image](https://github.com/tweedegolf/mailcrab/assets/35434094/3868bb25-861f-43fa-9cd6-304bcb34be58)

Yes, I will delete **this** comment after an update of the issue report.

Point that I'm trying to make:   _Please put effort in reporting issues_

**Comment by Stygmates** [comment]
Yes that was a mistake in me pasting the code, it can happen to anyone, but I feel like the description is clear enough to understand the issue, here's the working container:
```
docker run --rm -p 1080:1080 -p 1025:1025 marlonb/mailcrab:latest
```

**Comment by stappersg** [comment]
![image](https://github.com/tweedegolf/mailcrab/assets/35434094/5ff6d65f-13b2-4174-b53e-9626b93a99b3)

**Comment by marlonbaeten** [comment]
Thank you @Stygmates.

When TLS is enabled `curl` should also send the message over TLS. Try using something like this:

```sh
curl -k --ssl-reqd smtps://127.0.0.1:1025 --mail-from myself@example.com --mail-rcpt receiver@example.com --upload-file samples/normal.email --user 'user:pass'
```

The `--ssl-reqd` parameter makes sure the SMTP connection is tunneled over TLS. The `-k` parameter makes curl accept self-signed certificates (which you probably use in a development setting).
