### ISSUE TITLE
Certificate not printed

### ISSUE THREAD

**Issue by irgeek** [tweedegolf/mailcrab#112]
The README states:

> You can enable TLS and authentication by setting the environment variable ENABLE_TLS_AUTH=true. MailCrab will generate a key-pair and print the self-signed certificate.

With the latest version, though, the certificate is no longer printed. All I see in the logs is this:

```
2024-02-08T08:14:04.442398Z  INFO mailcrab_backend::smtp::tls: Generating self-signed certificate...
2024-02-08T08:14:04.443203Z  INFO mailcrab_backend::smtp::tls: TLS configuration loaded
```

It would be great to get this behaviour back as it made standing MailCrab up for quick tests much simpler.

**Comment by marlonbaeten** [comment]
Sorry about that - the log statement got lost during a rewrite. I've added it again en will release it with version 1.1 in a few minutes.

On a side note, the certificate is also written to disk, so you can find it there, but I guess that might be ergonomic in some cases.
