### ISSUE TITLE
logging of expire deletion

### ISSUE THREAD

**Issue by stappersg** [tweedegolf/mailcrab#115]
The events of incoming email and API delete email are being logged.

Deletion of email due expire, age > `MAILCRAB_RETENTION_PERIOD`, is **not** logged.

**Comment by stappersg** [comment]
I have tried to find where to insert the missing `event!()`, but failed. Would like to get clues where to look closer.    :wink:

**Comment by marlonbaeten** [comment]
Hi Geert. In the storage module https://github.com/tweedegolf/mailcrab/blob/main/backend/src/storage.rs#L45 all messages are filtered with using `retain`. You could give the closure a body and add the log statement there. Any PR is welcome :-)

**Comment by stappersg** [comment]
On Mon, Feb 26, 2024 at 12:06:05PM -0800, Marlon wrote:
> Closed #115 as completed via #116.


Thanks.   Even faster as I could write "way above my rust skill level"



Groeten
Geert Stappers
-- 
Silence is hard to parse
