### ISSUE TITLE
API endpoints to delete all messages and delete single message

### ISSUE THREAD

**Issue by elitemaks** [tweedegolf/mailcrab#119]
It would be great if there is a simple endpoint like api/delete and api/delete/{id} to delete all or a single message.
It would greatly help with test automation so users can clear their inboxes before executing new tests.

**Comment by marlonbaeten** [comment]
Hi @elitemaks 

See https://github.com/tweedegolf/mailcrab/pull/120/files
Was that what you had in mind?

**Comment by elitemaks** [comment]
Hi @marlonbaeten , yes, that is exactly what I need. Thanks for the quick reply!

**Comment by marlonbaeten** [comment]
Released in https://github.com/tweedegolf/mailcrab/releases/tag/v1.2.0
