### ISSUE TITLE
Test send mail when "ENABLE_TLS_AUTH=true" is failed!.

### ISSUE THREAD

**Issue by pakinming** [tweedegolf/mailcrab#125]
I run ENABLE_TLS_AUTH and run test `curl` below is not work
```sh
docker run -d --rm --env ENABLE_TLS_AUTH=true -p 3000:1080 -p 2525:1025 marlonb/mailcrab:latest
```
```sh
curl -k --ssl-reqd smtp://127.0.0.1:2525 --mail-from mail-from@cli-test.com --mail-rcpt receiver@cli-test.com --upload-file ./mail-tp.html --user 'user:pass'
```

mail not sending!!
![Screenshot 2567-10-31 at 15 31 01](https://github.com/user-attachments/assets/8da9e610-3353-4ea0-9968-92873afa78c6)

**Comment by marlonbaeten** [comment]
I think you need to specify the protocol as `smtps` when using TLS.

Try this:
```
curl -k --ssl-reqd smtps://127.0.0.1:2525 --mail-from mail-from@cli-test.com --mail-rcpt receiver@cli-test.com --upload-file ./mail-tp.html --user 'user:pass'
```

Please reopen this issue if that does not fix your problem.
