### ISSUE TITLE
Links open in IFrame

### ISSUE THREAD

**Issue by siemendev** [tweedegolf/mailcrab#14]
Hi folks,
really nice you provide a solution for the not-touched-in-2-years mailhog (that has no arm image on dockerhub).

When receiving mails in mailcrab, opening links in those mails will not open them in the top frame but in the little iframe, where the mail is displayed.

I would be fine with links opening in a new tab by default.

Thanks for the effort you've put into this, really appreciate it!

Kind regards
Patrick

**Comment by marlonbaeten** [comment]
Thank you Patrick! I have just pushed an update that solves the issue with link targets :+1:
