### ISSUE TITLE
Running mailcrab with a prefix behind a proxy

### ISSUE THREAD

**Issue by kevinvalk** [tweedegolf/mailcrab#15]
Hei, I saw the LinkedIn post and I immediately jumped on this (as I was using MailHog and a MacBook M1), great job!

That said, in our current setup we had all dev tools behind a proxy (MailHog was at `localhost:8001/smtp`). MailCrab does not support running from a different prefix and will instead grab files from `http://localhost:8001/mailcrab-frontend-520e3bc03b391c36.js` even though it should be `http://localhost:8001/smtp/mailcrab-frontend-520e3bc03b391c36.js`.

Is it something you can and want to support?

**Comment by marlonbaeten** [comment]
Thank you for your feeback :-)

Would an environment variable (like `MAILCRAB_PATH_PREFIX`) that enables mailcrab to run on the specified path resolve your issue?

**Comment by kevinvalk** [comment]
Could work, or make imports relative to current path (can be hard). Then it does not matter what the base URL is.

**Comment by marlonbaeten** [comment]
Well, there are also calls to the API and the websocket endpoint, if these were relative the backend does not know on which path to serve the API. So configuring the path explicitly would solve that problem.

**Comment by marlonbaeten** [comment]
I’ve implemented this in v0.5.0
