### ISSUE TITLE
Mailcrab and Lettre

### ISSUE THREAD

**Issue by ianpurton** [tweedegolf/mailcrab#17]
I've been using Mailhog in development and I switched it with Mailcrab.

I'm using [lettre](https://github.com/lettre/lettre) to send email.

I use the following code to send email https://github.com/purton-tech/barricade/blob/master/crates/actix-server/src/email.rs

with the following creds

```
SMTP_HOST: smtp
SMTP_PORT: 1025
SMTP_USERNAME: thisisnotused
SMTP_PASSWORD: thisisnotused
SMTP_TLS_OFF: 'true'
```

I get 

```rust
Could not send email: lettre::transport::smtp::Error { kind: Client, source: "No compatible authentication mechanism was found" }
```

Is there something obvious I'm missing.

Thanks for building this BTW it looks really great.

**Comment by marlonbaeten** [comment]
You can look at my test at https://github.com/tweedegolf/mailcrab/blob/main/backend/src/main.rs#L121 in which I also use lettre to send mail to mailcrab. I think your code should work if you leave out the credentials in https://github.com/purton-tech/barricade/blob/master/crates/actix-server/src/email.rs#L11

I've also assed #19 to allow passing credentials.

**Comment by ianpurton** [comment]
@marlonbaeten That would be great thanks. I think it makes it easier for people moving over from Mailhog which is what I was trying to do.
