### ISSUE TITLE
Dedicated tab for displaying the plain/text part?

### ISSUE THREAD

**Issue by spantaleev** [tweedegolf/mailcrab#22]
I'm sending emails with both `text/html` and `text/plain` mime parts.

The MailCrab UI shows me the HTML email in the **Formatted** tab, and I can probably look at the plain part in **Raw**, but it's not very convenient.

It'd be nice to have a dedicated **Plain** tab which shows the `text/plain` version.

**Comment by marlonbaeten** [comment]
I've added this in v0.7.0 (latest):

![image](https://user-images.githubusercontent.com/885089/223209095-453c139c-8289-4c7c-b0b8-a57913beddcb.png)
