### ISSUE TITLE
Image does not shut down cleanly in Docker

### ISSUE THREAD

**Issue by a3957273** [tweedegolf/mailcrab#25]
When running Mailcrab in docker-compose, the image does not cleanly shut down.  It waits 10 seconds, whereupon Docker forcibly kills it.  You should listen to the `SIGINT` and `SIGTERM` signals and shut down the application. 

I don't have an example for rust, but in JavaScript:

```
process.on('SIGINT', () => {
  console.info('SIGINT signal received: Interrupted')
  process.exit(0)
})

export function registerSigTerminate(httpServer: any) {
  process.on('SIGTERM', () => {
    console.info('SIGTERM signal received: closing HTTP server')
    httpServer.close(() => {
      console.log('')
    })
  })
}
```

P.S. Love Mailcrab, displays emails so well compared to our previous application!

**Comment by marlonbaeten** [comment]
Fixed in version v0.9.0
