### ISSUE TITLE
Net::SMTPAuthenticationError: 503 Bad sequence of commands 

### ISSUE THREAD

**Issue by dedene** [tweedegolf/mailcrab#31]
Thanks a lot for your work, Mailcrab looks nice!

I tried to use it as a drop in replacement for Mailcatcher, but I'm getting `Net::SMTPAuthenticationError: 503 Bad sequence of commands` probably because the SMTP library tries to authenticate. Is it possible to add support for this (without actual authentication, but just accepting the messages)?

**Comment by marlonbaeten** [comment]
This is added in v0.10.0 thanks to @tk-nguyen - just set the environment variable `ENABLE_TLS_AUTH=true`

**Comment by dedene** [comment]
Awesome, many thanks for this! It works great, however I needed to make one adjustment to be able to replace our old internally used mailcatcher with mailcrab: use a real valid TLS certificate (generated with cert-manager).

I made PR #35 that checks if a cert.pem and key.pem already exist (i.e. by mounting them from a Kubernetes secret) and skips the generation of a self signed certificate if they are present. Feel free to suggest any changes to the code if needed.

**Comment by dedene** [comment]
@marlonbaeten @tk-nguyen I still see "Bad sequence of commands" errors when using it as a drop-in replacement for Mailcatcher. Maybe I'll explain our use case: we run an internal instance, where only the smtp ports are public. This allows our team members to use a (sort-off) throw-away email address for debugging and testing purpose, which keeps the personal and shared inboxes clean from all these test messages. 

When connecting to Mailcrab from i.e. a Rails of Phoenix application, that works fine with the added TLS option. But a provider like Sendgrid or Gmail is getting "Bad sequence of commands". In the logs I find `websocket error Error { inner: Protocol(ResetWithoutClosingHandshake) }` but I'm not 100% sure if that is related as my Rust knowledge is not that elaborated.

Any idea if I can help to find a solution for this? I really like the project, the fresh and snappy UI and love to move it forward so it can fully replace mailcatcher (which is a bit unmaintained last years).

**Comment by tk-nguyen** [comment]
> @marlonbaeten @tk-nguyen I still see "Bad sequence of commands" errors when using it as a drop-in replacement for Mailcatcher. Maybe I'll explain our use case: we run an internal instance, where only the smtp ports are public. This allows our team members to use a (sort-off) throw-away email address for debugging and testing purpose, which keeps the personal and shared inboxes clean from all these test messages.
> 
> When connecting to Mailcrab from i.e. a Rails of Phoenix application, that works fine with the added TLS option. But a provider like Sendgrid or Gmail is getting "Bad sequence of commands". In the logs I find `websocket error Error { inner: Protocol(ResetWithoutClosingHandshake) }` but I'm not 100% sure if that is related as my Rust knowledge is not that elaborated.
> 
> Any idea if I can help to find a solution for this? I really like the project, the fresh and snappy UI and love to move it forward so it can fully replace mailcatcher (which is a bit unmaintained last years).

Can you try running `mailcrab` with `RUST_LOG` environment variable set to `debug`? After that, you can attach the logs here. Please make sure to not include any sensitive information.
