### ISSUE TITLE
Convert new line characters to br tag

### ISSUE THREAD

**Issue by jokaorgua** [tweedegolf/mailcrab#38]
Hello. It would be pretty nice to convert new line characters in webUI to <br> tag in HTML

Or at least have such an option.

current behavior
if we have text
```
this is 
text with new line
```

it will be displayed in webUI as
```
this istext with new line
```

**Comment by marlonbaeten** [comment]
Plain-text e-mail bodies will now be wrapped in a `<pre>` tag, which should render newlines as intended.
This will be releases in v0.12.0
