### ISSUE TITLE
Unable to send multiple emails

### ISSUE THREAD

**Issue by farazfazli** [tweedegolf/mailcrab#40]
To reproduce, run the following code inside an actix-web route (adapted from Lettre example, just testing things out here):
```
    let email = Message::builder()
        .from("Test <nobody@test.example>".parse().unwrap())
        .reply_to("Test <nobody@test.example>".parse().unwrap())
        .to("Bob <bob@test.example>".parse().unwrap())
        .subject("Happy new year!!")
        .header(ContentType::TEXT_PLAIN)
        .body(String::from("Be happy!!!"))
        .unwrap();

    let mailer = SmtpTransport::builder_dangerous("127.0.0.1")
        .port(1025)
        .build();

    // Send the email
    match mailer.send(&email) {
        Ok(_) => println!("Email sent successfully!"),
        Err(e) => panic!("Could not send email: {e:?}"),
    }
    return HttpResponse::Ok().finish();
```

First email sends successfully, subsequent emails cause the following error:

```
thread 'actix-rt|system:0|arbiter:1' panicked at 'Could not send email: lettre::transport::smtp::Error { kind: Network, source: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" } }', src/routes/users.rs:27:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt|system:0|arbiter:0' panicked at 'Could not send email: lettre::transport::smtp::Error { kind: Network, source: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" } }', src/routes/users.rs:27:19
```

The Docker container is still running fine. Any idea what could be causing this?

**Comment by marlonbaeten** [comment]
I do not think the error is related to the performance / availability of MailCrab itself. I've used your example code to do a little throughput test. Sending the above message 100x to MailCrab takes about 4 seconds on my machine. This scales lineair to 1000 messages.

Based on the error message it looks like a docker network error. Have you tried upgrading docker / restarting the docker daemon?

**Comment by farazfazli** [comment]
You're right, this is an issue tied to the pooling I'm performing and not related to mailcrab.

**Comment by stappersg** [comment]
Now that #49 has been fixed, it would make sense to retry the test from this issue.
