### ISSUE TITLE
Have less real  test email addresses

### ISSUE THREAD

**Issue by stappersg** [tweedegolf/mailcrab#42]
Hi,

Yeah, tests should be a real as possible. And yes, tests should just remain tests.

Currently there a "real" test addresses.

![image](https://user-images.githubusercontent.com/35434094/229349753-95ae1eaa-b6ee-4121-9e65-ae2cd4d3cd00.png)

This feels wrong.

Please replace the  _gmail_ and _hotmail_ email addresses with bogus ones.

**Comment by stappersg** [comment]
Meanwhile I found this
```rust
#[cfg(test)]
mod test {
    use crate::get_env_port;
    use crate::types::MailMessageMetadata;
    use fake::faker::company::en::{Buzzword, CatchPhase};
    use fake::faker::internet::en::FreeEmail;
    use fake::faker::lorem::en::Paragraph;
    use fake::faker::name::en::Name;
    use fake::Fake;
```
in `backend/src/main.rs`. I think it is the line
```rust
    use fake::faker::internet::en::FreeEmail;
```
that causes the "trouble". `(` Free (gratuit) Email causing again trouble  `;-)`

Leaving the issue open for now.  ( For furhter feedback )

**Comment by marlonbaeten** [comment]
Hi @stappersg. Thanks for the suggestion.
Note that these e-mail addresses are randomly generated and only used in a functional test. They are never published (apart from the screenshot your shared) or used in any other way.
I'm curious how this could lead to "trouble" in our case - are there any scenarios i'm missing? If so- there might be a reason to also file an issue for the https://crates.io/crates/fake crate.

**Comment by stappersg** [comment]
The "trouble" is _"Why real email addresses in a test???"_.  The _missing scenario_ is
> There are people exposed to "real" email addresses without knowing where they come from , without knowing they are supposed be be "internal use only".

At https://docs.rs/fake/2.5.0/fake/?search=mail did I found `SafeEmail`.

Closing this issue in favor of Merge Request #43.

**Comment by epilys** [comment]
FYI RFC2506 reserves specific domain names only for documentation and testing use.

https://www.rfc-editor.org/rfc/rfc2606.html#page-2

**Comment by marlonbaeten** [comment]
Sure, I'll merge #43
