### ISSUE TITLE
UI title is not updated

### ISSUE THREAD

**Issue by jokaorgua** [tweedegolf/mailcrab#45]
When we have an email in our inbox we see in the title of the webpage (N) MailCrab, where N is the number of new emails

After clicking the Remove All button the title is not updated and is left with (N). To update a title the page must be reloaded.

**Comment by jokaorgua** [comment]
Same thing when new mail has been received. The title is (1), when new mail is received and you don't activate the tab with mailcrab the title does not change. When you click on the tab, the new mail appears in the list, but the title is still (1) but should be (2)

**Comment by marlonbaeten** [comment]
This should be fixed with #48
